/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This document records options that can be passed to Dithermark-node
 */
export interface DithermarkNodeOptions {
  /**
   * Image filtering properties
   */
  image?: {
    preDither?: {
      pixelate?: number;
      brightness?: number;
      smooth?: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 10 | 12 | 14 | 16;
    };
  };
}
